name: COBOL Check Automation V1.8

run-name: ${{github.actor}} has triggered ${{github.workflow}}

on:
  push:
    branches: [ main ]
    paths: ['**.CBL' , '**.JCL']
    
  workflow_dispatch:
      inputs:
          run_zowe:
              description: 'Run ZOWE?'
              type: choice
              options:
                    - 'Y'
                    - 'N'
              required: false
              default: 'Y'
jobs:
  cobol-check:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    env:
        ZOWE_CLI_HOME: "/home/runner/work/cobol-check-automation/cobol-check-automation/.github/.zowe"
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}

    steps:
    
    - uses: actions/checkout@v4

    - name: init
      run: |
        echo "Running Cobol Check Workflow"
        echo "Zowe home=$ZOWE_CLI_HOME"
        cd $GITHUB_WORKSPACE
        ls -la
        echo "-----DT---"
        cd $ZOWE_CLI_HOME
        ls -la
        echo "-----DT2---"
        ls -la `$ZOWE_CLI_HOME`
        echo "-----DT3---"
        cd /home/runner/work/cobol-check-automation/cobol-check-automation/.github/.zowe
        echo $(pwd)
        ls -la
        echo "---------done runner-----"
        
#    - name: Set up Java
#      uses: actions/setup-java@v2 
#      with:
#        java-version: '11'
#        distribution: 'adopt'

 #   - name: Check node
 #     run: node -v
      
    - name: Install ZOWE CLI
      run: npm install -g @zowe/cli@latest

    - name: check_zowe_config
      run: zowe config list

    - name: setup_lowercase username
      run: |
        LOWERCASE_USERNAME=$(echo "$ZOWE_USERNAME" | tr '[:upper:]' '[:lower:]')
        echo "lowercase un=$LOWERCASE_USERNAME"
        echo "LOWERCASE_USERNAME=$LOWERCASE_USERNAME" >> $GITHUB_ENV

    - name: Check if USS files exist
      run: |
        rtn_sts=false
        zowe zos-files list uss-files "/z/$LOWERCASE_USERNAME/cobolcheck" --u $ZOWE_USERNAME --pw $ZOWE_PASSWORD && rtn_sts=true
        echo "return=$rtn_sts"
        echo "cobolcheck_exists=$rtn_sts" >> $GITHUB_ENV
    
    - name: Setup Mainframe USS Environment and Upload COBOL Check
      if: env.cobolcheck_exists != true
      run: |
        chmod +x .github/scripts/zowe_operations_t.sh
        .github/scripts/zowe_operations_t.sh
        
    - name: Run COBOL Check on Mainframe
      run: |
        echo "---> mainframe ops"
        chmod +x .github/scripts/mainframe_operations.sh
        .github/scripts/mainframe_operations.sh

    - name: Done
      run: echo "Done"

