name: COBOL Check Automation V1.0

run-name: ${{github.actor}} has triggered ${{github.workflow}}

on:
  push:
    branches: [ main ]
    paths: ['**.CBL' , '**.JCL']
    
  workflow_dispatch:

jobs:
  cobol-check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
        ZOWE_CLI_HOME: ".github/.zowe"
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}

    steps:
    
    - uses: actions/checkout@v3

    - name: init
      run: |
        echo "Running Cobol Check WOrkflow"
        echo "home=$ZOWE_CLI_HOME"
        
#    - name: Set up Java
#      uses: actions/setup-java@v2 
#      with:
#        java-version: '11'
#        distribution: 'adopt'

 #   - name: Check node
 #     run: node -v
      
    - name: Install ZOWE CLI
      run: npm install -g @zowe/cli@latest
        
    - name: Setup Mainframe Environment and Upload COBOL Check
#      env:
#        ZOWE_OPT_HOST:               204.90.115.200
#        ZOWE_OPT_PORT:               10443
#        ZOWE_OPT_USERNAME:           ${{ secrets.ZOWE_USERNAME }}
#        ZOWE_OPT_PASSWORD:           ${{ secrets.ZOWE_PASSWORD }}
#        ZOWE_OPT_REJECT_UNAUTHORIZED: false
#        ZOWE_USERNAME:               ${{ secrets.ZOWE_USERNAME }}
#        ZOWE_PASSWORD:               ${{ secrets.ZOWE_PASSWORD }}
      run: |
        echo "---> zowe ops"
        # Here we'll add our commands to setup cobolcheck
        chmod +x .github/scripts/zowe_operations_t.sh
        ls -l .github/scripts/
        zowe zos-files list ds $ZOWE_USERNAME  --user $ZOWE_USERNAME  --password $ZOWE_PASSWORD
     #   .github/scripts/zowe_operations_t.sh
        # Add actual cobolcheck commands here
        
    - name: Run COBOL Check on Mainframe
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      # Here we'll add our commands to setup cobolcheck
      #  sshpass -p "$ZOWE-PASSWORD" ssh -o "StrictHostKeyChecking"=no $ZOWE_USERNAME@204.90.115.200 'sh -s' < .github/scripts/mainframe_operations.sh
      run: |
        echo "---> mainframe ops"
        chmod +x .github/scripts/mainframe_operations_t.sh
        .github/scripts/mainframe_operations_t.sh
      # Add actual cobolcheck commands here

    - name: Done
      run: echo "Done"

