name: Workflow Test 01

run-name: ${{github.actor}} has triggered this workflow

on:
  push:
    branches: [ main ]
    paths: ['**.txt' , '**.DOC']

jobs:
  gwf-test01:
    runs-on: ubuntu-latest
    steps:
    - name: gwf_name01
      run: echo "Hi World"
      
      
