name: Upload and compile a COBOL pgm on Z/OS V1.5
#
# for a program specified on input:
# upload a JCL and CBL file to PDS datasets on Z/OS mainframe
# then run the JCL to compile the program
#
run-name: ${{github.actor}} has triggered ${{github.workflow}}

on:
#  push:
#    branches: [ main ]
#    paths: ['**.CBL' , '**.JCL']
    
  workflow_dispatch:
   inputs:
       pgm_name:
              description: 'Program name?'
              type: string
              required: true

  repository_dispatch:
   inputs:
          pgm_name:
              description: 'Program name?'
              type: string
              required: true

jobs:
  cobol-compile:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
        ZOWE_CLI_HOME: ".github/.zowe"
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}

    steps:
    
    - uses: actions/checkout@v4

    - name: init
      run: |
        echo "Running upload and compile Cobol"
        echo "Param=${{ github.event.inputs.pgm_name }}"
        echo "home=$ZOWE_CLI_HOME"
      
    - name: Install ZOWE CLI
      run: npm install -g @zowe/cli@latest
      
    - name: build_params
      env:
        ZOWE_DOT:      "."
        ZOWE_CBL_PDS:  "CBL"
      run: |
        echo "VAR_CBL_PDS=$ZOWE_USERNAME$ZOWE_DOT$ZOWE_CBL_PDS" >> $GITHUB_ENV

    - name: Upload the CBL
      run: |
        rtn_sts=false
        zowe zos-files list am $VAR_CBL_PDS --u $ZOWE_USERNAME --pw $ZOWE_PASSWORD && rtn_sts=true
        echo "return=$rtn_sts"
        echo "zowe_sts=$rtn_sts" >> $GITHUB_ENV
    

    - name: Done
      run: echo "Done"
